### ISSUE TITLE
5.5.3. Aggregation packet - v3c-tile-id-pres

### ISSUE THREAD

**Issue by lkondrad** [laurilo/draft-ilola-avtcore-rtp-v3c#11]
> If v3c-tile-id-pres is equal to 2 and the AU NAL unit header type is in range 0-35, inclusive, the 16-bit v3c-tile-id field MUST be present in the aggregation unit after the conditional DOND/DONL field. Otherwise v3c-tile-id field MUST NOT be present in the aggregation unit.

change to 

> If v3c-tile-id-pres is equal to **1** and the AU NAL unit header type is in range 0-35, inclusive, the 16-bit v3c-tile-id field MUST be present in the aggregation unit after the conditional DOND/DONL field. Otherwise v3c-tile-id field MUST NOT be present in the aggregation unit.

**Comment by laurilo** [comment]
No need to fix the text, maybe just update the discsription better in the optional parameters section.
