### ISSUE TITLE
Clause 3 - Unused/Unspecified Abbreviations and Definition 

### ISSUE THREAD

**Issue by lkondrad** [laurilo/draft-ilola-avtcore-rtp-v3c#15]
Unused:
* atlas frame parameter set
* AFPS
* atlas sequence parameter set
* ASPS
* intra random access point coded atlas
* intra random access point coded atlas access unit
* CAS - It is unused in the text only used once in the definition, so we can remove the abbreviation and use coded atlas sequence in definition of atlas bitstream

Unspecified 
* CVS

Through the document we have V3C atlas bitstream, but in clause 3 we specify atlas bitstream. Should we remove V3C in front of atlas bitstream through out the text ?

**Comment by laurilo** [comment]
unused references were removed.

Added definition of CVS

Removed V3C from the front of V3C atlas bitstream and consistely refer to atlas bitstream through out the document.

**Comment by laurilo** [comment]
Resolved with https://github.com/laurilo/draft-ilola-avtcore-rtp-v3c/commit/11780da5bd1f9d23b42bca258d973b0ad123e432
